In [1]:
import pandas as pd
import numpy as np
import os
import csv
import matplotlib.pyplot as plt


In [2]:
# load data

X_train = pd.read_csv("./song_features/X_train.csv")
y_train = pd.read_csv("./song_features/y_train.csv")
X_val = pd.read_csv("./song_features/X_val.csv")
y_val = pd.read_csv("./song_features/y_val.csv")
X_test = pd.read_csv("./song_features/X_test.csv")

X_train = X_train.iloc[:,2:]
X_val = X_val.iloc[:,2:]
X_test = X_test.iloc[:,2:]

# turn array
X_train = np.array(X_train)
y_train = np.array(y_train)
X_val = np.array(X_val)
y_val = np.array(y_val)
X_test = np.array(X_test)

# turn y, since wanna treat this problem as a classification problem
label_y_train=y_train.astype(np.int)
label_y_val=y_val.astype(np.int)

matrix_y_train = np.zeros((np.shape(y_train)[0],5))
matrix_y_val = np.zeros((np.shape(y_val)[0],5))

# print(np.shape(y_train)[0])

for i in range(np.shape(y_train)[0]):
    matrix_y_train[i][label_y_train[i]-1]=1
print("DONE processing y_train")
    
for i in range(np.shape(y_val)[0]):
    matrix_y_val[i][label_y_val[i]-1]=1
print("DONE processing y_val")

DONE processing y_train
DONE processing y_val


In [3]:
# get shape

Xtrain_shape = np.shape(X_train)
ytrain_shape = np.shape(y_train)
Xval_shape = np.shape(X_val)
yval_shape = np.shape(y_val)
Xtest_shape = np.shape(X_test)
matrixytrain_shape = np.shape(matrix_y_train)
matrixyval_shape = np.shape(matrix_y_val)
labelytrain_shape = np.shape(label_y_train)
labelyval_shape = np.shape(label_y_val)
print(Xtrain_shape,ytrain_shape,Xval_shape,yval_shape,Xtest_shape,matrixytrain_shape,matrixyval_shape,labelytrain_shape,labelyval_shape)

(150232, 57) (150232, 1) (50077, 57) (50077, 1) (50078, 57) (150232, 5) (50077, 5) (150232, 1) (50077, 1)


In [4]:
# sklearn for classification:
# https://scikit-learn.org/stable/modules/multiclass.html
# https://scikit-learn.org/stable/auto_examples/ensemble/plot_adaboost_multiclass.html
# https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html

In [5]:
# # adaboost
# from sklearn.model_selection import cross_val_score
# from sklearn.ensemble import AdaBoostClassifier
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.datasets import make_gaussian_quantiles
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score

# bdt_real = AdaBoostClassifier(
#     DecisionTreeClassifier(max_depth=2),
#     n_estimators=50,
#     learning_rate=1)

# bdt_discrete = AdaBoostClassifier(
#     DecisionTreeClassifier(max_depth=2),
#     n_estimators=50,
#     learning_rate=1.5,
#     algorithm="SAMME")

# print("start bdt_real")
# bdt_real.fit(X_train, label_y_train)
# print("start bdt_discrete")
# bdt_discrete.fit(X_train, label_y_train)

# print("start predict real")
# y_pred_real = bdt_real.predict(X_train)

# print("start predict discrete")
# y_pred_discrete = bdt_discrete.predict(X_train)






In [6]:
# # show result
# print('Training error of sklearn real AdaboostClassifier: %.2f' % (1-accuracy_score(label_y_train, y_pred_real)))
# print('Training error of sklearn discrete AdaboostClassifier: %.2f' % (1-accuracy_score(label_y_train, y_pred_discrete)))

# print(y_pred_discrete[0:50])
# print(y_pred_real[0:50])
# # print(label_y_train[0:20])

In [7]:
# binary classification
# # Create and fit an AdaBoosted decision stump
# bdt = AdaBoostClassifier(DecisionTreeClassifier(max_depth=2),
#                          algorithm="SAMME.R",
#                          n_estimators=50)
# print("begin training")
# bdt.fit(X_train, matrix_y_train[:,2])
# print("begin predicting")
# y_pred = bdt.predict(X_train)
# print('Training error of sklearn AdaboostClassifier: %.2f' % (1-accuracy_score(matrix_y_train[:,2], y_pred)))
# y_pred = bdt.predict(X_val)
# print('Testing error of sklearn AdaboostClassifier: %.2f' % (1-accuracy_score(matrix_y_val[:,2], y_pred)))



In [8]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import optimizers

/Users/EmilyW./anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [9]:
# build model
model = Sequential()
# model.add(Dense(output_dim=128, input_dim=57, activation='relu'))
# model.add(Dense(output_dim=64, input_dim=128, activation='relu'))
# model.add(Dense(output_dim=32, input_dim=64, activation='relu'))
# model.add(Dense(output_dim=32, input_dim=57, activation='sigmoid'))
# model.add(Dense(output_dim=64, input_dim=57, activation='sigmoid'))
model.add(Dense(output_dim=10, input_dim=57, activation='sigmoid'))
model.add(Dropout(0.2))
# model.add(Dense(8, activation='relu'))
model.add(Dense(output_dim=5, input_dim=10, activation='softmax'))


/Users/EmilyW./anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=57, activation="sigmoid", units=10)`
  
/Users/EmilyW./anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=10, activation="softmax", units=5)`
  # This is added back by InteractiveShellApp.init_path()


In [10]:
# # compile model
sgd = optimizers.SGD(lr=0.005, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mean_squared_error', optimizer='sgd', metrics=['accuracy'])
# model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [11]:
print(matrix_y_train)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]


In [12]:

# fit model
model.fit(X_train, matrix_y_train, epochs=50, batch_size=256)

Epoch 1/50
150232/150232 [==============================] - 3s 20us/step - loss: 0.1586 - acc: 0.3182: 0s - loss: 0.1591 - acc
Epoch 2/50
150232/150232 [==============================] - 2s 11us/step - loss: 0.1532 - acc: 0.3432
Epoch 3/50
150232/150232 [==============================] - 2s 12us/step - loss: 0.1517 - acc: 0.3414
Epoch 4/50
150232/150232 [==============================] - 2s 12us/step - loss: 0.1508 - acc: 0.3417
Epoch 5/50
150232/150232 [==============================] - 2s 12us/step - loss: 0.1503 - acc: 0.3426
Epoch 6/50
150232/150232 [==============================] - 3s 22us/step - loss: 0.1499 - acc: 0.3422: 1s -
Epoch 7/50
150232/150232 [==============================] - 2s 11us/step - loss: 0.1497 - acc: 0.3405
Epoch 8/50
150232/150232 [==============================] - 2s 12us/step - loss: 0.1494 - acc: 0.3426:
Epoch 9/50
150232/150232 [==============================] - 2s 11us/step - loss: 0.1492 - acc: 0.3431
Epoch 10/50
150232/150232 [=======================

In [13]:
y_res = model.predict(X_train)
y_resval = model.predict(X_val)

In [14]:
y_pred = y_res.argmax(axis=-1)+1
y_predval = y_resval.argmax(axis=-1)+1
# print(y_res[0:20])
print(y_pred[0:20])
print(np.transpose(y_train[0:20]))
print(y_predval[0:20])
print(np.transpose(y_val[0:20]))

[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[[4. 5. 5. 4. 5. 5. 5. 4. 4. 4. 5. 2. 4. 5. 5. 3. 5. 5. 4. 3.]]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[[2. 5. 5. 5. 4. 5. 2. 5. 4. 4. 5. 3. 5. 1. 4. 5. 2. 5. 3. 4.]]


In [45]:
# # keras prediction

# # example of training a final regression model
# from keras.models import Sequential
# from keras import optimizers
# from keras.layers import Dense, Dropout
# from sklearn.datasets import make_regression
# from sklearn.preprocessing import MinMaxScaler
# # # generate regression dataset
# # X, y = make_regression(n_samples=100, n_features=2, noise=0.1, random_state=1)
# # scalarX, scalarY = MinMaxScaler(), MinMaxScaler()
# # scalarX.fit(X)
# # scalarY.fit(y.reshape(100,1))
# # X = scalarX.transform(X)
# # y = scalarY.transform(y.reshape(100,1))
# # define and fit the final model
# model = Sequential()
# model.add(Dense(25, input_dim=57, activation='linear'))
# model.add(Dropout(0.5))
# model.add(Dense(12, activation='linear'))
# model.add(Dropout(0.5))
# model.add(Dense(6, activation='linear'))
# model.add(Dropout(0.5))
# model.add(Dense(3, activation='linear'))
# model.add(Dropout(0.5))
# model.add(Dense(1, activation='linear'))
# # model.compile(loss='mse', optimizer='sgd')
# sgd = optimizers.SGD(lr=0.005, decay=1e-6, momentum=0.9, nesterov=True)
# model.compile(loss='mean_squared_error', optimizer='adam')
# model.fit(X_train, y_train, epochs=10)
# # model.compile(loss='mean_squared_error', optimizer='sgd')
# # model.fit(X_train, y_train, epochs=20)

In [46]:
# y_res = model.predict(X_train)

In [47]:
# print(y_res[0:10])
# print(y_train[0:10])

In [31]:
# # sklearn multiclass classification sample
# print(__doc__)

# # Author: Noel Dawe <noel.dawe@gmail.com>
# #
# # License: BSD 3 clause

# from sklearn.externals.six.moves import zip

# import matplotlib.pyplot as plt

# from sklearn.datasets import make_gaussian_quantiles
# from sklearn.ensemble import AdaBoostClassifier
# from sklearn.metrics import accuracy_score
# from sklearn.tree import DecisionTreeClassifier


# X, y = make_gaussian_quantiles(n_samples=13000, n_features=10,
#                                n_classes=3, random_state=1)

# n_split = 3000

# print(np.shape(y))

# X_train, X_test = X[:n_split], X[n_split:]
# y_train, y_test = y[:n_split], y[n_split:]

# bdt_real = AdaBoostClassifier(
#     DecisionTreeClassifier(max_depth=2),
#     n_estimators=600,
#     learning_rate=1)

# bdt_discrete = AdaBoostClassifier(
#     DecisionTreeClassifier(max_depth=2),
#     n_estimators=600,
#     learning_rate=1.5,
#     algorithm="SAMME")

# bdt_real.fit(X_train, y_train)
# bdt_discrete.fit(X_train, y_train)

# real_test_errors = []
# discrete_test_errors = []

# for real_test_predict, discrete_train_predict in zip(
#         bdt_real.staged_predict(X_test), bdt_discrete.staged_predict(X_test)):
#     real_test_errors.append(
#         1. - accuracy_score(real_test_predict, y_test))
#     discrete_test_errors.append(
#         1. - accuracy_score(discrete_train_predict, y_test))

# n_trees_discrete = len(bdt_discrete)
# n_trees_real = len(bdt_real)

# # Boosting might terminate early, but the following arrays are always
# # n_estimators long. We crop them to the actual number of trees here:
# discrete_estimator_errors = bdt_discrete.estimator_errors_[:n_trees_discrete]
# real_estimator_errors = bdt_real.estimator_errors_[:n_trees_real]
# discrete_estimator_weights = bdt_discrete.estimator_weights_[:n_trees_discrete]

# plt.figure(figsize=(15, 5))

# plt.subplot(131)
# plt.plot(range(1, n_trees_discrete + 1),
#          discrete_test_errors, c='black', label='SAMME')
# plt.plot(range(1, n_trees_real + 1),
#          real_test_errors, c='black',
#          linestyle='dashed', label='SAMME.R')
# plt.legend()
# plt.ylim(0.18, 0.62)
# plt.ylabel('Test Error')
# plt.xlabel('Number of Trees')

# plt.subplot(132)
# plt.plot(range(1, n_trees_discrete + 1), discrete_estimator_errors,
#          "b", label='SAMME', alpha=.5)
# plt.plot(range(1, n_trees_real + 1), real_estimator_errors,
#          "r", label='SAMME.R', alpha=.5)
# plt.legend()
# plt.ylabel('Error')
# plt.xlabel('Number of Trees')
# plt.ylim((.2,
#          max(real_estimator_errors.max(),
#              discrete_estimator_errors.max()) * 1.2))
# plt.xlim((-20, len(bdt_discrete) + 20))

# plt.subplot(133)
# plt.plot(range(1, n_trees_discrete + 1), discrete_estimator_weights,
#          "b", label='SAMME')
# plt.legend()
# plt.ylabel('Weight')
# plt.xlabel('Number of Trees')
# plt.ylim((0, discrete_estimator_weights.max() * 1.2))
# plt.xlim((-20, n_trees_discrete + 20))

# # prevent overlapping y-axis labels
# plt.subplots_adjust(wspace=0.25)
# plt.show()